### ISSUE TITLE
Prefer `return()` over relying on R to implicitly return result

### ISSUE THREAD

**Issue by 11rchitwood** [tidyverse/style#131]
The [section on `return()`](https://style.tidyverse.org/functions.html#return) says:
> Only use return() for early returns. Otherwise, rely on R to return the result of the last evaluated expression.

And has the following (adbridged) example:
```r
# Good
add_two <- function(x, y) {
  x + y
}

# Bad
add_two <- function(x, y) {
  return(x + y)
}
```
Typing less is nice, but our Python colleagues would say:
> Explicit is better than implicit.

Relying on R to return the result of the last evaluated expression *is* explicit, but I think using `return()` is *more* explicit. It's very nice to scan a function definition looking for every instance of `return()` to quickly get an idea of possible outputs.

I considered creating this issue in [tidyverse/principles](https://github.com/tidyverse/principles), as PEP 20 is brought up there, but I stuck with this repo since the guidelines on this topic appear here.

**Comment by hadley** [comment]
Returning the last evaluated expression is an absolutely key part of the R language — if you don't understand this you are going to find it hard to understand much code in the wild. Since you have to know this, I think it's much more important to reserve `return()` to signal early returns for exceptional conditions.
