### ISSUE TITLE
Closing brace for double-indented function declaration

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/style#202]
## styler and this style guide

```r
x <- function(
    a,
    b) {
}
```

## codegrip

```r
x <- function(
    a,
    b
) {
}
```

## Problem

This inconsistency makes it difficult to use codegrip with styler. Can we get a consensus here? The desired outcome would be to allow both forms, or to even switch to recommending the second form. This is fairly easy to change in styler, I can help here.

**Comment by MichaelChirico** [comment]
See https://github.com/tidyverse/style/issues/173#issuecomment-904073980 as well as discussion on the implementing PR.

this was already proposed and rejected IIUC.

**Comment by krlmlr** [comment]
Thanks for the heads-up.

**Comment by krlmlr** [comment]
The current version of codegrip cycles between one line, single indent, and hanging indent on my machine. Can you confirm?

**Comment by jrosell** [comment]
I can confirm that {codegrip} permits single-indent, but the issue here is that if I have this code:
long_function_name <- function(
  a = "a long argument",
  b = "another argument",
  c = "another long argument"
) {
  # Body
}

It gets modified by default styler function to this code:
long_function_name <- function(
    a = "a long argument",
    b = "another argument",
    c = "another long argument") {
  # Body
}

If not possible/desired as a default, it could be a thing that I would like to configure.

**Comment by krlmlr** [comment]
Not after https://github.com/r-lib/styler/pull/1235 😁
