### ISSUE TITLE
Clarify reasoning behind %<>% proscription

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#203]
I was doubting myself while wording the lint for the operator in https://github.com/r-lib/lintr/pull/2020. Currently the guide just says "don't use it" without much else.

It would be preferable to at least have a short blurb on why this operator is taboo. IIRC I've read somewhere the main idea is the in-place-ish assignment is antithetical to a strong functional approach encouraged elsewhere in Tidyverse.

**Comment by hadley** [comment]
This may be more obvious post #188, since there is no base R equivalent.

Overall, I'd say that assignment is such an important concept that you want to make it as explicit as possible, and the best way to do that is to use the standard assignment operator. So in that sense, maybe it's related to the rule of not using `=` for assignment?
