### ISSUE TITLE
pipes followed by ggplot layers:  why should all ggplot layers have same level of indentation as pipe lines?

### ISSUE THREAD

**Issue by david-romano** [tidyverse/style#210]
From the second paragraph of [5.2 Whitespace](https://style.tidyverse.org/ggplot2.html#whitespace-1):

> If you are creating a ggplot off of a dplyr pipeline, there should only be one level of indentation. 

Why is this?  The unique role of the initial `ggplot()` statement suggests that all further added statements should always be indented in the way suggested by the first paragraph of [5.2 Whitespace](https://style.tidyverse.org/ggplot2.html#whitespace-1):

> `+` should always have a space before it, and should be followed by a new line. [...] After the first step, each line should be indented by two spaces.

**Comment by hadley** [comment]
Because `+` and `|>` play the same role. If ggplot2 was created today, it would likely use `|>` instead of `+`.

**Comment by jeffkimbrel** [comment]
Sorry to comment on a closed issue, but I tend to agree with @david-romano. From what I know, ggplot and `+` is basically a dead-end that you can't "escape" out of. In other words, once you `|>` to ggplot, you don't then pipe the ggplot object to other functions. This makes ggplot distinct from other tidyverse functions that both accept piped input, and pass on an object that can further be manipulated by other functions. Even `ggsave` doesn't really accept a ggplot object from `|>` since the plot object is the second argument (I know there's a way around this).

An extra level of indentation makes it clear to me that it has reached some terminus.
